briandfoy/module-release

- lib/Module/Release.pm
- lib/Module/Release/Prereq.pm
Checks the value of makefile_PL config setting to determine this.
Without this, the prereqs check fails on my Build.PL based distro.
> Module/Release/Prereq.pm - use Test::Prereq::Build when appropriate

- lib/Module/Release.pm
I found a couple of instances of the older two-arg form of `open()` being used and have updated the code to use the three-arg form here.  The tests still pass and Travis seems happy with the change as well.
This PR is submitted in the hope that it is useful.  If you have any questions or comments concerning it, please let me know and I can update and resubmit as necessary.
> Use three-arg form of open()

- t/dist_version.t
Perlcritic noticed that the loop variable changed here wasn't scoped to
the loop it refers to.  This change fixes the variable's scope.
> Restrict loop variable scope to loop

- script/release
I noticed that the copyright year mentioned in the release script wasn't consistent with the copyright year mentioned in other files.  This updates the information so that all files now contain consistent copyright information.
> Update copyright year in release script

- lib/Module/Release.pm
- lib/Module/Release/FTP.pm
- lib/Module/Release/Kwalitee.pm
- lib/Module/Release/MANIFEST.pm
- lib/Module/Release/PAUSE.pm
- lib/Module/Release/Prereq.pm
- lib/Module/Release/SVN.pm
- lib/Module/Release/WebUpload/Mojo.pm
- script/release
It turns out that the 'H' in 'GitHub' is supposed to be capitalised.
This change fixes all occurrences to use the style used by GitHub
itself.
I happened to notice this issue while spell checking the documentation.  Hope it's alright to make this change.
> Fix GitHub capitalisation

- lib/Module/Release.pm
- lib/Module/Release/FTP.pm
- lib/Module/Release/Prereq.pm
- lib/Module/Release/SVN.pm
Just some typos I spotted by running a spell checker over the source files containing POD.
> Fix typos in POD and comments

- Makefile.PL
- lib/Module/Release.pm
- script/release
- t/dates.t
The release date given in the Changes file should conform to the
format defined in CPAN::Changes::Spec.  Although the code in the
`release` script already conformed to this spec, it's nicer to have the
functionality wrapped in a method.  These changes add the new
`get_release_date()` method as well as tests for it, and replace the
existing code in the `release` script with the new method call.
> Return release date string via get_release_date() method

- Makefile.PL
- t/passwords.t
... in order to document the method's current behaviour.
> Add tests for check_for_passwords() method

- t/lib/setup_common.pl
Perlcritic had actually noticed that a variable was being assigned to within a conditional statement, however looking at the code I noticed that the `$error` variable was never being used, hence this PR.  If you actually intended for this line of code to perform some purpose other than that done by the `ok()` and `diag()` calls later in the code then I'd be really interested in the reason why the code with the `$error` variable was included; I wouldn't expect you to add such code unless it was necessary for some reason, and I have the vague feeling I'm missing something subtle here.
> Remove unused variable

- script/release
This is probably the last renmant of the variable name change from "cvs"
to "vcs" which happened in version 2.00_07, and it looks like this one
simply got missed.
> Rename cvs_commit -> vcs_commit

- t/dist_version.t
While reading the test code I noticed that the `dist_version` method was
being called directly in the test check and hence the temporary variable
wasn't needed and hence can be removed.
> Remove unused variable '$got' in dist_version tests

- lib/Module/Release/Kwalitee.pm
The cpants_lint.pl program has been extracted into a separate project
and hence one needs `App::CPANTS::Lint` in order that the kwalitee tests
in `Module::Release` can be run.  Here I've extracted the required
module names into variables to try and be more descriptive, but also to
reduce the length of the strings required in the `eval` and in the `die`
message.
> Require App::CPANTS::Lint for kwalitee checks

- t/changes.t
These tests attempt to document the current behaviour of the
`get_changes()` method.
Interestingly enough, this PR probably creates more questions than it tries to answer.  My goal was to increase the code coverage, however in creating the tests I noticed that the implementation of the `get_changes()` method doesn't really match the documentation for the method in that it doesn't really seem to parse the whole `Changes` file; it seems to just read the title/header text at the top and return that.  Furthermore, the `get_changes()` method isn't used anywhere in the dist; not even in the `release` script.  It also doesn't read and parse the `Changes` file for the dist itself, so I'm guessing that something changed in the in past to make the method no longer relevant.
I would guess that you …
> Add tests for get_changes() method

- lib/Module/Release.pm
It's not being used anywhere anymore.  It seems that it used to be used
as part of the release process to SourceForge, however that no longer
seems to be relevant, hence the code is superfluous and can go.
> Remove the get_readme() method

- hack/mojo.pl
- t/compile.t
- t/load.t
- t/no_releaserc_can_die.t
- t/pod.t
- t/pod_coverage.t
- xt/changes.t
Perlcritic noticed that strictures were missing in some files.  The missing strictures have been added in these commits, which I've separated according to directory just in case you wish to cherry pick the changes.
This PR is submitted in the hope that it is useful.  If you have any questions or comments about it, please don't hesitate to let me know, and if you wish for anything to be changed I'll update the PR as appropriate and resubmit.
> Add missing strictures

- t/dist_version.t
These tests check for the issue mentioned in GH #5, namely that version
numbers such as 1.001 should not be reduced to 1.01.
Unfortunately, it seems that the issue mentioned in #5 isn't an issue anymore.  Perhaps these changes are useful to document that, or perhaps I've missed something.  Either way, here's the code, hope it helps in some way!
> Check that version numbers can be more than 2dp

- Makefile.PL
- lib/Module/Release.pm
- t/get_env_var.t
- t/input.t
I used `Module::Release` to automate the release of one of my modules and was a bit shocked to find my PAUSE password being echoed to the terminal.  Hence, I tested and refactored the `get_env_var()` method so that when one is asked to set the `CPAN_PASS` variable, the password isn't echoed to the screen.  The code for this I adapted from `CPAN::Uploader`.  If you have any questions or comments, or want to discuss how I've implemented this, please feel free!  If you want to have anything changed I can update the PR and resubmit as necessary.
> Avoid echoing password to terminal

- Makefile.PL
- lib/Module/Release.pm
- script/release
- t/contributors.t
These changes implement two routines which fulfill the desired feature
mentioned in #11: one to print the list of recent contributors
(`show_recent_contributors()`) and one to obtain the list of recent
contributors from the relevant version control system
(`get_recent_contributors()`).  The `get_recent_contributors()` method
is only a stub and needs to be overridden by the appropriate mixin for
the given version control system.  A concrete implementation of this
method will be submitted in a separate PR to the `Module::Release::Git`
repository.
> Show list of contributors since previous release

- lib/Module/Release.pm
- script/release
- t/lib/setup_common.pl
Perlcritic mentions that using `:encoding(UTF-8)` is better practice than simply using `:utf8` in I/O operations.  This PR fixes the issue and hence removes the perlcritic warning.
This PR is submitted in the hope that it is useful. If you have any questions or comments about it, please don't hesitate to let me know, and if you wish for anything to be changed I'll update the PR as appropriate and resubmit.
> Replace :utf8 with :encoding(UTF-8) for strict I/O validation

- script/release
• Support parallel testing by `-j`, `-j4`, `--jobs`, `--jobs=8`, and `.releaserc[test_jobs]`
• Add long options
• Remove duplicate `$release->dist_version`
I did not add to Changes, as that looks generated
> Enable parallel testing

- Makefile.PL
- lib/Module/Release.pm
- script/release
- script/release-test
This includes skipping `cpan_version_check`, as it depends on running `dist`
When running `release -t` on 400 versions of perl, dist checks and mere annoying and certainly not helpful
> Skip ->dist if $skip_dist
